### ISSUE TITLE
Move to enzyme org?

### ISSUE THREAD

**Issue by ljharb** [preactjs/enzyme-adapter-preact-pure#100]
Since preact already has an org, it might not be practical to maintain access in a separate org, but I wanted to at least file the issue.

Now that enzyme is in its own github org (https://github.com/enzymejs), would you be interested in moving this adapter to that org? Of course permissions would remain the same, and yall would be able to add anyone to the org/github team you wanted.

**Comment by robertknight** [comment]
Thanks for the info @ljharb and the ongoing maintenance of Enzyme. The Preact Enzyme adapter is currently more coupled to implementation details of Preact 10 (eg. see [this file](https://github.com/preactjs/enzyme-adapter-preact-pure/blob/master/src/preact10-rst.ts) and [this one](https://github.com/preactjs/enzyme-adapter-preact-pure/blob/master/src/preact10-internals.ts)) than it is to Enzyme, assuming that Enzyme's "adapter" API is pretty stable. For that reason I think it makes sense to keep it in the Preact org.

I'd like to decouple the adapter better from Preact internals in future, so it may be worthwhile to revisit this then.

**Comment by ljharb** [comment]
Sounds good; let me know if anything changes.
