### ISSUE TITLE
compatibility issue with typescript and function component

### ISSUE THREAD

**Issue by AvivM96** [preactjs/enzyme-adapter-preact-pure#101]
Hey, im using enzyme-adapter-preact-pure in preact project with typescript, everything works well until I'm using **React** function component (not class component) I'm getting this type error - 

`Error:(5, 9) TS2605: JSX element type 'ReactElement<any, string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)>) | (new (props: any) => Component<any, any, any>)>' is not a constructor function for JSX elements.
  Type 'ReactElement<any, string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)>) | (new (props: any) => Component<any, any, any>)>' is missing the following properties from type 'Element': nodeName, attributes, children
`

preact runs this component with no issue, what should i do ?

**Comment by qyjandroid** [comment]
![image](https://user-images.githubusercontent.com/6645414/79539954-e820f300-80b9-11ea-9931-ec1866364573.png)
![image](https://user-images.githubusercontent.com/6645414/79539989-f66f0f00-80b9-11ea-99bd-7f615cff7fe3.png)
