### ISSUE TITLE
Typescript example still does not work

### ISSUE THREAD

**Issue by mike-lischke** [preactjs/enzyme-adapter-preact-pure#234]
This is not a duplicate of issue #198. Tests build, run and succeed in a terminal. However they do not in VS Code, because of conflicting React types:

<img width="729" alt="Bildschirm­foto 2022-12-09 um 10 35 21" src="https://user-images.githubusercontent.com/2398704/206671351-149cadd5-583b-49e4-b101-683edcefc1f1.png">

The error is:

```
No overload matches this call.
  Overload 1 of 3, '(node: ReactElement<any, string | JSXElementConstructor<any>>, options?: MountRendererProps | undefined): ReactWrapper<...>', gave the following error.
    Argument of type 'Element' is not assignable to parameter of type 'ReactElement<any, string | JSXElementConstructor<any>>'.
      Types of property 'type' are incompatible.
        Type 'string | ComponentType<any>' is not assignable to type 'string | JSXElementConstructor<any>'.
          Type 'ComponentClass<any, {}>' is not assignable to type 'string | JSXElementConstructor<any>'.
            Type 'ComponentClass<any, {}>' is not assignable to type 'new (props: any) => Component<any, any, any>'.
              Property 'refs' is missing in type 'Component<any, {}>' but required in type 'Component<any, any, any>'.
  Overload 2 of 3, '(node: ReactElement<any, string | JSXElementConstructor<any>>, options?: MountRendererProps | undefined): ReactWrapper<...>', gave the following error.
    Argument of type 'Element' is not assignable to parameter of type 'ReactElement<any, string | JSXElementConstructor<any>>'.
  Overload 3 of 3, '(node: ReactElement<any, string | JSXElementConstructor<any>>, options?: MountRendererProps | undefined): ReactWrapper<...>', gave the following error.
    Argument of type 'Element' is not assignable to parameter of type 'ReactElement<any, string | JSXElementConstructor<any>>'.ts(2769)
index.d.ts(507, 9): 'refs' is declared here.
```

This is the typescript example straight checked-out, initialized and opened in VS Code.

**Comment by mike-lischke** [comment]
Seems to be related to https://github.com/preactjs/preact/issues/1206.

**Comment by rschristian** [comment]
As you discovered, I believe this is more of an issue with Preact itself and Typescript.

Enzyme, if I'm recalling correctly, will (unfortunately) drag in `@types/react` which starts a bit of a conflict. While the Preact types should be fixed (if possible), that's always going to present a bit of an issue as they can easily become out of sync. As such, I added the recommendation to use the `"paths"` entry of users' `tsconfig.json` to help ensure the types used are the correct ones.

**Comment by rschristian** [comment]
> What surprises me most is that the workaround does not work in the typescript example folder

Odd, can't reproduce any issue with the typescript example even without the aliasing. Using neovim (w/ the TS language server) though, might be a VSCode issue?

FWIW, setting `"paths"` isn't a workaround, it's aliasing React to Preact in a way that TS can be aware of. It's not any different from aliasing in a bundler and will be needed to support Preact-specific typings used w/ React libraries. Just wanted to clarify.

> (which btw. has a wrong readme, pointing to a "counter" folder and pointing to that folder in the readme of it is also weird, given that the readme is exactly in this folder slightly_smiling_face)

Oops, good shout. Will get that fixed.

**Comment by mike-lischke** [comment]
> FWIW, setting `"paths"` isn't a workaround, it's aliasing React to Preact in a way that TS can be aware of. It's not any different from aliasing in a bundler and will be needed to support Preact-specific typings used w/ React libraries. Just wanted to clarify.

That shouldn't be necessary as it is a manual task that can easily be forgotten (especially by beginners in this area), but that's what we have to live with. Thanks!

**Comment by rschristian** [comment]
> That shouldn't be necessary as it is a manual task

I'm not sure I understand; how would TypeScript be aware that you want to consume Preact's types in place of React's? Any automatic solution (shared namespaces or allowing modules to override others' types) would completely erode type safety. It needs to be a manual process else you (rightfully) wouldn't trust any of your libraries' types, as they may be altering each other behind the scenes.

While this specific situation certainly seems like it could be avoided with some corrections to Preact's types, it's only a stop-gap solution as one would still be using the incorrect types for the actual backing JS. Not sure if there's anything more we can do though.
