### ISSUE TITLE
Jest encountered an unexpected token catch { SyntaxError: Unexpected token {import { configure } from "enzyme";

### ISSUE THREAD

**Issue by Arun12Muralidharan** [preactjs/enzyme-adapter-preact-pure#260]
I'm facing the below problem while running test case. 

Code can be found on -> https://github.com/Arun12Muralidharan/team_tracker
Its a part of mini project (hacker rank), uses very old node version (v8.15.1) and npm (v6.4.1)
I had completed coding part, but unable to show the results of the test case.

As its to be done in web ide, I cannot edit package.json, Tests  dir, *.sh files.
Could someone help me in fixing the issue ? (Error screenshot attached).

**Error Message**

 ```
FAIL  src/Tests/Login.test.js
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /projects/challenge/node_modules/cheerio/dist/commonjs/api/attributes.js:300
            catch {
                  ^

    SyntaxError: Unexpected token {

      4 | // learn more: https://github.com/testing-library/jest-dom
      5 | // import '@testing-library/jest-dom/extend-expect';
    > 6 | import { configure } from "enzyme";
        | ^
      7 | import Adapter from "enzyme-adapter-react-16";
      8 | configure({ adapter: new Adapter() });
      9 |

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:579:25)
      at Object.<anonymous> (node_modules/cheerio/src/cheerio.ts:6:1)
      at Object.<anonymous> (node_modules/cheerio/src/load.ts:7:1)
      at Object.<anonymous> (node_modules/cheerio/src/load-parse.ts:1:1)
      at Object.<anonymous> (node_modules/cheerio/src/index.ts:6:1)
      at Object.<anonymous> (node_modules/enzyme/src/Utils.js:9:1)
      at Object.<anonymous> (node_modules/enzyme/src/ReactWrapper.js:4:1)
      at Object.<anonymous> (node_modules/enzyme/src/index.js:1:1)
      at Object.<anonymous> (src/setupTests.js:6:1)
          at Array.forEach (<anonymous>)
```

![Error1](https://github.com/user-attachments/assets/af2878df-909e-45ef-961b-66280e51cedf)
![Error2](https://github.com/user-attachments/assets/6bb99be5-75d9-485b-9dc7-b53d18fafc29)
![Error3](https://github.com/user-attachments/assets/f1d5b7a8-5e7c-417f-9b3b-5e25583e4c49)
![Error4](https://github.com/user-attachments/assets/39b7eb9b-cbc3-488d-a66a-a4c87c26e0d7)
![Error5](https://github.com/user-attachments/assets/d1d2fa87-d512-4ecc-a932-44fe2a84c6b0)
![Error6](https://github.com/user-attachments/assets/adb5edf8-b9cc-43dd-a9ea-8b135330af62)
![Error7](https://github.com/user-attachments/assets/23f5aa26-7b60-4a78-aa7b-9d03b8ba2689)
![Error8](https://github.com/user-attachments/assets/91016109-7468-4197-a44f-29b69126d2a7)
![Error9](https://github.com/user-attachments/assets/30a64c68-fd63-4136-92b8-d6bcf8a19c96)

**Comment by robertknight** [comment]
The problem is the old version of Node. The code being highlighted is using a feature known as "optional catch binding" which allows writing `try { ... } catch { ... }` instead of `try { ... } catch (variableName) { ... }`. [According to MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch#browser_compatibility) this requires Node v10 or later.
