### ISSUE TITLE
Testing Stateful Functional Components

### ISSUE THREAD

**Issue by fabiodcorreia** [preactjs/enzyme-adapter-preact-pure#40]
Hi,

There is anyway to check the state of a functional component that implements the state with the hook useState? I tried the mount.state() but it says that can be only used on Class components.

I saw that Preact 10 now includes preact/test-utils that should help with this but I could find a way to use it with enzyme and get the state. 

My idea is to get the state and see if the values are what I expect. But maybe there are better way to test the component state.

**Comment by robertknight** [comment]
There is no way to directly retrieve state values created with `useState` at present or to call the setter returned by `useState`. If Enzyme gains support for this in future, I will aim to support it in this adapter.

My personal recommendation when writing tests is to treat hooks as an internal implementation detail and write your tests in terms of what the outside world/user sees (render output) and does (simulated events etc). This gives you the flexibility to change your implementation without having to modify the tests, as long as the end result is the same for the user. If testing via the rendered output alone is difficult, eg. because the logic for computing the state is complex, this might be a signal to extract that logic into a separate function which can be tested on its own.

The main important detail you need to know for testing things that use hooks is that state updates and effects happen asynchronously by default. The `act()` function from `preact/test-utils` can be used to make state updates/effects run synchronously.

The adapter will call `act()` at certain times to flush effects/state updates for you:

1. When calling `mount(...)` or `shallow(...)`
2. When dispatching an event via `wrapper.simulate(...)`
3. When calling an Enzyme function which causes Enzyme to re-render the component, eg. `wrapper.setProps(...)`

If however you do something which triggers a state change inside an Enzyme component without Enzyme being aware, for example using `wrapper.find('button').prop('onClick')()`, then you may need to wrap that code in an `act()` block in order to make scheduled state updates/effects run, and call `wrapper.update()` _after_ the `act()` block to make the wrapper reflect the current rendered tree.

For example:

```js
import { mount } from 'enzyme';
import { act } from 'preact/test-utils';

// 1. Executes state updates/effects for you
const wrapper = mount(<MyComponent/>);

// 2. Executes state updates/effects for you
const wrapper = mount(<MyComponent/>);
wrapper.find('button').simulate('click')

// 3. Executes state updates/effects for you
const wrapper = mount(<MyComponent/>);
wrapper.setProps({ label: 'foo' });

// 4. You must call `act()` yourself and then `wrapper.update()`
const wrapper = mount(<MyComponent/>);
act(() => {
  wrapper.find('button').prop('onClick')();
  // State updates/effects happen after this block returns
});
wrapper.update();
```

I hope this helps!

**Comment by fabiodcorreia** [comment]
Thanks @robertknight  that makes sense, I can check the props and then test the rendered html with the snapshots in most of the cases the html reflects the state so it should be sufficient.

**Comment by fabiodcorreia** [comment]
I'm not sure if this a problem of my implementation, a testing limitation or wrong testing implementation.

Let's say I have this component:

```javascript

export const Toast = (props: Props) => {
    const [isVisible, setVisible] = useState<boolean>(props.message ? true : false);
    if (!isVisible) {
        return null;
    }
    return (
        <ToastView
            message={props.message}
            onClose={() => {
                setVisible(false);
            }}
        />
    )
```
So if we have a props.message it's visible/render the component, if the message gets empty or the user click on close it turns invisible/doesn't render.

Then I have to scenarios to test

```javascript
it('should start open and close when user click on close', () => {
    const wrapper = mount(<Toast message='My Message'/>);
    expect(wrapper.props()).toEqual({ message: 'My Message', children: [] });
    expect(wrapper).toMatchSnapshot();
    wrapper.find('button.delete').simulate('click');
    expect(wrapper.props()).toEqual({ message: 'My Message', children: [] });
    expect(wrapper).toMatchSnapshot();
});
```
This scenario works fine, when I look the snapshot the HTML is just the top wrapper nothing else. For the second scenario it doesn't behave the same way.

```javascript
it('should start open and close when message gets empty', () => {
    const wrapper = mount(<Toast message='My Message'/>);
    expect(wrapper.props()).toEqual({ message: 'My Message', children: [] });
    expect(wrapper).toMatchSnapshot();
    const refresh = wrapper.setProps({message:''});
    // Also tried calling the wrapper.update() or refresh.update()
    expect(refresh.props()).toEqual({ message: '', children: [] });
    expect(refresh).toMatchSnapshot();
});
```
In this case the props.message is empty but when I look to the snapshot all the HTML is rendered there and not just the top wrapper, the message tag is empty but the rest is there.

I also put a console.log after setState to understand the problem and I get the following behavior
```javascript
const [isVisible, setVisible] = useState<boolean>(props.message ? true : false);
console.log(props.message + " >> " + isVisible);
// 'My Message' >> true
// Update message to empty
// '' >> true' but expected '' >> false'
```
The strange is the component works fine on storybook.

**Comment by robertknight** [comment]
The argument to `useState` is the initial state which is only used when the component is first rendered. On subsequent renders the previous state value is retained, and it only changes if you call `setVisible`. This is why it doesn't change when you call `wrapper.setProps`.

The React Hooks FAQ has an entry on how to implement [state derived from props](https://reactjs.org/docs/hooks-faq.html#how-do-i-implement-getderivedstatefromprops) that may be helpful here.

**Comment by robertknight** [comment]
I'm closing this issue as I think my comment above answers the question. Feel free to post additional comments though if you have further questions.

**Comment by fabiodcorreia** [comment]
@robertknight  Thanks for your help, what still confuses my is why on storybook it works fine when I change the prop it refresh the state. I will try the implementation suggested on the FAQ and see the result.

Again thanks for the quick replies.

**Comment by robertknight** [comment]
@fabiodcorreia - Is it possible that the component is being recreated in Storybook when you change props rather than just updating the existing instance?

**Comment by fabiodcorreia** [comment]
@robertknight That was the other thing that I was thinking but meanwhile I did some more discovery with the Hooks FAQ that you suggested. I implemented the prevState and added a counter to identify the number of the render and more logs.

```javascript
let index = 0;

const Toast = (props: Props) => {
    index++;
    const i = index;
    const [isVisible, setVisible] = useState<boolean>(props.message ? true : false);
    const [prevMessage, setPrevMessage] = useState<string | undefined>(props.message);
    console.log(
        `Render #${i} - Start Render with message '${
            props.message
        }' and isVisible '${isVisible}' and prev message '${prevMessage}'`
    );

    if (props.message !== prevMessage) {
        console.log(`Render #${i} - SetVisible`);
        setVisible(props.message ? true : false);
        console.log(`Render #${i} - SetPrevMessage`);
        setPrevMessage(props.message);
    }

    console.log(
        `Render #${i} - End Render with message '${
            props.message
        }' and isVisible '${isVisible}' and prev message '${prevMessage}'`
    );
    if (!isVisible) {
        return null;
    }
    return (
        <ToastView
            type={props.type || ToastType.INFO}
            position={props.position || ToastPosition.CENTER_CENTER}
            message={props.message}
            onClose={() => {
                setVisible(false);
            }}
        />
    );
};
```
Then I get this output

```console
Render #1 - Start Render with message 'My Toast Message' and isVisible 'true' and prev message 'My Toast Message'
Render #1 - End Render with message 'My Toast Message' and isVisible 'true' and prev message 'My Toast Message'
Render #2 - Start Render with message '' and isVisible 'true' and prev message 'My Toast Message'
Render #2 - SetVisible
Render #3 - Start Render with message '' and isVisible 'false' and prev message 'My Toast Message'
Render #3 - SetVisible
Render #3 - SetPrevMessage
Render #4 - Start Render with message '' and isVisible 'false' and prev message ''
Render #4 - End Render with message '' and isVisible 'false' and prev message ''
Render #3 - End Render with message '' and isVisible 'false' and prev message 'My Toast Message'
Render #2 - SetPrevMessage
Render #2 - End Render with message '' and isVisible 'true' and prev message 'My Toast Message'
```

The render 2 which is the one that should change the visibility get's the second part executed after 3 and 4 and that causes the problem.

```console
Render #1 - Start Render with message 'My Toast Message' and isVisible 'true' and prev message 'My Toast Message'
Render #1 - End Render with message 'My Toast Message' and isVisible 'true' and prev message 'My Toast Message'
Render #2 - Start Render with message '' and isVisible 'true' and prev message 'My Toast Message'
Render #2 - SetPrevMessage
Render #3 - Start Render with message '' and isVisible 'true' and prev message ''
Render #3 - End Render with message '' and isVisible 'true' and prev message ''
Render #2 - SetVisible
Render #4 - Start Render with message '' and isVisible 'false' and prev message ''
Render #4 - End Render with message '' and isVisible 'false' and prev message ''
Render #2 - End Render with message '' and isVisible 'true' and prev message 'My Toast Message'
```
Also if I change the order of setVisible and setPrevMessage the steps are different but still render 2 finish the execution at the end of 3 and 4.
