### ISSUE TITLE
ReferenceError: h is not defined

### ISSUE THREAD

**Issue by ijones922** [preactjs/enzyme-adapter-preact-pure#43]
Getting this error and trying to execute your example code provided in the repo. I get the h is not defined error. My test is just normal js file

```
import { mount } from 'enzyme';

const wrapper = mount(<div class="widget"/>);
wrapper.props() // Returns `{ children: [], className: 'widget' }`
wrapper.find('.widget').length // Returns `1`
```
  I have this in my babelrc as well which is supposed to help with this issue:
```
{
    "plugins": [
      [
        "transform-react-jsx",
        {
          "pragma": "h"
        }
      ]
    ]
  }
```
```
 ReferenceError: h is not defined

       9 | // })
      10 |
    > 11 | const wrapper = mount(<div class="widget"/>);
         |                           ^
      12 | wrapper.props() // Returns `{ children: [], className: 'widget' }`
      13 | wrapper.find('.widget').length // Returns `1`
      14 |
```

**Comment by ijones922** [comment]
figured this out and realized i wasn't importing { h } from 'preact' into the test

**Comment by robertknight** [comment]
Thanks for the feedback. This issue made me realize that there are no complete examples in the README or repository which would be useful for newcomers. I've filed https://github.com/preactjs/enzyme-adapter-preact-pure/issues/44 as a task to create some and update the documentation.
