### ISSUE TITLE
Errors when using simulate() api

### ISSUE THREAD

**Issue by ingro** [preactjs/enzyme-adapter-preact-pure#45]
Hello! I'm trying to test the behaviour of a checkbox component.

```js
    test('should call onChange callback when clicked', () => {
        const spy = jest.fn();

        const context = mount(<Checkbox name="foo" onChange={spy} />);

        context.find('input').simulate('change', { target: { value: true } });

        expect(spy).toHaveBeenCalledWith('foo', true);
    });
```

But calling the `simulate` api causes me multiple problems. 

First I had this error:

```
ReferenceError: Event is not defined
at MountRenderer.Object.<anonymous>.MountRenderer.simulateEvent (node_modules/enzyme-adapter-preact-pure/build/src/MountRenderer.js:101:21)
```

which I resolved by putting Event in the global namespace in my setup file:

```js
const jsdom = new JSDOM('<!doctype html><html><body></body></html>');
const { window } = jsdom;

global.Event = window.Event;
```

But then I got another error:

```
TypeError: Cannot set property target of #<Event> which has only a getter
at MountRenderer.Object.<anonymous>.MountRenderer.simulateEvent (node_modules/enzyme-adapter-preact-pure/build/src/MountRenderer.js:106:16)
```

If I pass as arg a random key the error is not thrown but of course the test fail:

```js
context.find('input').simulate('change', { foo: 'bar' });
```

For reference I'm using latest Preact (v10.0.0-beta.1) and latest enzyme-adapter-preact-pure (v1.13.1).

**Comment by robertknight** [comment]
`simulate(...)` dispatches a real `Event` object to the target DOM element using `domElement.dispatchEvent(event)`, so the value of `target` is set on the event for you and you can't change it. What you can do is get a reference to the DOM node and modify it before dispatching the event using `wrapper.find(...).getDOMNode()`.

This is currently a difference from the React Enzyme adapters which, AFAIK, don't actually dispatch a real event.

Does this answer your question?

**Comment by ingro** [comment]
Well yes, thanks for your time and for the explanation. Maybe it could be worth to add a gotcha on the readme cause [the official enzyme documentation](https://airbnb.io/enzyme/docs/api/ReactWrapper/simulate.html) suggest another way to handle events.

**Comment by robertknight** [comment]
I have added some notes about differences between Enzyme + React and Enzyme + Preact in [the README](https://github.com/preactjs/enzyme-adapter-preact-pure/blob/master/README.md#differences-compared-to-enzyme--react) which covers this.

I think in future it may make sense to change the behaviour to match the React adapters, but that would be a breaking change so I have simply documented it for now.

**Comment by mutoe** [comment]
I had the same problem. 

What should I do when I test functional component like this?

``` tsx
export default function Login() {
  const [ form, setForm ] = useState({ email: '' })

  return (
    <form>
      <input value={form.email} placeholder="Email" onInput={e => setForm({ email: e.currentTarget.value })}>

      <button disabled={!form.email}>Login</button>
    </form>
  )
}
```

``` tsx
  it('should set button enabled when form is valid', function () {
    const wrapper = shallow(<Login />)
    wrapper.find('[placeholder="Email"]').simulate('input', { currentTarget: { value: '123' } })

    const loginButton = wrapper.find('form button.btn-lg.btn-primary')
    expect(loginButton.props().disabled).toBe(false)
  })
```

I can't change the internal state if I can't simulate event. Is there anything wrong with me? @robertknight  @ingro

**Comment by mutoe** [comment]
I might add, when I try to use 
```ts
wrapper.find('[placeholder="Email"]').getDOMNode<HTMLInputElement>().value = '123'
```

I got an error `TypeError: wrapper.find(...).getDOMNode is not a function`

**Comment by robertknight** [comment]
@mutoe - You can't get a reference to the DOM node if you use `shallow` to render the component. This is a limitation that is unfortunately inherited from the way React's shallow rendering works. You need to use the `mount` function instead.

At work, we combine the advantages of `mount` rendering (full access to the DOM) with those of `shallow` rendering (having a unit test that is isolated from the details of its child components) by using a [Babel plugin](https://github.com/robertknight/babel-plugin-mockable-imports) to mock imported components. The [React docs](https://reactjs.org/docs/testing-recipes.html#mocking-modules) recommend doing something conceptually similar with Jest.

**Comment by mutoe** [comment]
@robertknight Thanks for your answer, `mount` solved my problem. I will try to use plugins to optimize my tests as you suggest later.

By the way, can `getDOMNode` be removed from the shallow wrapper in TS ?

**Comment by akellbl4** [comment]
@robertknight I made a small patch which provides an opportunity to pass `{target}` to `simulate()` as second argument. It is a bit hacky but works. What do you think about it?
