### ISSUE TITLE
Argument of type Element is not assignable

### ISSUE THREAD

**Issue by tombell** [preactjs/enzyme-adapter-preact-pure#46]
I'm trying to migrate my project over to preact 10.0.0 and enzyme/enzyme-adapter-preact-pure, however I'm having trouble with types.

## Component

```typescript
import { h, Component } from 'preact';
import { RoutableProps } from 'preact-router';

import { Tracklist, FetchTracklists } from '../services/memoir/types';

import TracklistItem from '../components/TracklistItem';

interface Props extends RoutableProps {
  fetchTracklists: FetchTracklists;
}

interface State {
  isLoading: boolean;
  tracklists: Tracklist[] | null;
}

export default class TracklistsPage extends Component<Props, State> {
  constructor(props: Props) {
    super(props);
    this.state = { isLoading: false, tracklists: null };
  }

  async componentWillMount() {
    // ...
  }

  renderTracklists() {
    // ...
  }

  render() {
    // ...
  }
}
```

## Test

```typescript
import { h } from 'preact';
import { mount, configure } from 'enzyme';
import { Adapter } from 'enzyme-adapter-preact-pure';
import test from 'ava';

import TracklistsPage from '../../src/pages/Tracklists';

import { FetchTracklists } from '../../src/services/memoir/types';

configure({ adapter: new Adapter() });

test('renders empty tracklists component', async t => {
  const fetchStub: FetchTracklists = () => new Promise(resolve => resolve([]));

  const wrapper = mount(<TracklistsPage fetchTracklists={fetchStub} />);

  // TODO: implement proper tests

  t.truthy(wrapper, 'TODO');
});
```

Error message

```
  Uncaught exception in test/pages/Tracklists.test.tsx

  test/pages/Tracklists.test.tsx:12:25 - error TS2345: Argument of type 'Element' is not assignable to parameter of type 'ReactElement<any, string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)> | null) | (new (props: any) => Component<any, any, any>)>'.
    Types of property 'type' are incompatible.
      Type 'string | ComponentClass<any, {}> | FunctionComponent<any> | null' is not assignable to type 'string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)> | null) | (new (props: any) => Component<any, any, any>)'.
        Type 'null' is not assignable to type 'string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)> | null) | (new (props: any) => Component<any, any, any>)'.

  12   const wrapper = mount(<TracklistsPage fetchTracklists={fetchStub} />);
                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by tombell** [comment]
Seems to be related when I have installed `@types/enzyme` and has `strict: true` in my `tsconfig.json`.

**Comment by robertknight** [comment]
The fundamental problem here is that the `@types/enzyme` package references types from the "react" package (`ReactElement` and others) which it seems are not 100% compatible with the corresponding types from the "preact" package. I think the ideal solution here would be to align the types so that `mount(h(...))` just works in a project that uses @types/enzyme. This would also resolve the issue with other packages which depend upon @types/react.

In the meantime you can work around this by using a [type assertion](https://basarat.gitbooks.io/typescript/docs/types/type-assertion.html). For example:

```ts
import { h } from 'preact';
import { mount } from 'enzyme';

mount(<MyWidget .../> as any)
```

**Comment by robertknight** [comment]
I would appreciate input from people more familiar with TypeScript + Preact about the various options for resolving this.

**Comment by tombell** [comment]
@robertknight thanks for the reply, I can definitely use the `as any` as a work around for now.

**Comment by Hubro** [comment]
I'm having the same issue with `shallow(...)`:

```typescript
it("triggers onLogin when the user presses submit", () => {
    const onLoginMock = jest.fn();

    // ERROR: Wrong type
    const form = shallow(<LoginForm onLogin={onLoginMock} />);

    form.find('input[type="submit"]').simulate("click");

    expect(onLoginMock.mock.calls.length).toEqual(1);
});
```

I suspect I'm going to have many such issues as I keep trying to use preact and TypeScript... I agree this should be fixed in `@types/enzyme`. If Enzyme supports third party adapters, so should the types.

I would offer to help, but I don't have anywhere near enough experience with either Typescript or Enzyme.

Meanwhile I suppose I'll have to work around with with `as any`... :(

**Comment by 38elements** [comment]
My pointing out may be wrong.
Using this type definition of enzyme may be resolve this issue.
IMHO, I think it is good to improve this file.

https://github.com/preactjs/enzyme-adapter-preact-pure/blob/bd74988199ad4ebe96dca1a5801e7fa600c83e40/types/enzyme/index.d.ts

You put this file to `types/enzyme/index.d.ts`.

tsconfig.json

```json
{
  "compilerOptions": {
    // ...
    "typeRoots": ["types"]
  }
}
```

**Comment by robertknight** [comment]
See ongoing work in https://github.com/preactjs/enzyme-adapter-preact-pure/pull/84.

**Comment by robertknight** [comment]
There is a solution for this in the latest (v2.2.0) release. Please see [this comment](https://github.com/preactjs/enzyme-adapter-preact-pure/issues/81#issuecomment-552179978) for details.
