### ISSUE TITLE
Debounce install hook doesn't work for Preact X RC1

### ISSUE THREAD

**Issue by lowaa** [preactjs/enzyme-adapter-preact-pure#68]
The conditional code in installHook to handle the Preact X case, breaks for the RC1 release.

The comment there says only applicable for an old Preact X beta build, which I assume isn't that relevant anymore?

Example output:

![image](https://user-images.githubusercontent.com/3772160/62593717-58139280-b90a-11e9-8ae6-e800db73fafc.png)

I've just deleted the Preact X conditional section and it seems to work fine: https://github.com/lowaa/enzyme-adapter-preact-pure/blob/master/src/debounce-render-hook.ts

Didn't make a PR because this will break for the beta build of Preact X

**Comment by robertknight** [comment]
> The conditional code in installHook to handle the Preact X case, breaks for the RC1 release.

Enzyme's own tests are passing with the latest Preact 10 RC under Node, so there must be something specific to the environment here.

I'd guess that something in your build tooling is freezing the exports of the "preact/test-utils" package to prevent them being mutated, which would mimic a restriction that real ES6 imports have.

In any case, there is no need for this workaround any more so I'll remove it.
