### ISSUE TITLE
Tests only work for functional components but fail for class components

### ISSUE THREAD

**Issue by psabharwal123** [preactjs/enzyme-adapter-preact-pure#92]
in Adapter.ts, isValidElement checks for -
```
if (
      typeof el.type !== 'string' &&
      typeof el.type !== 'function' &&
      el.type !== null
    ) {
      return false;
    }
```
but type is always undefined for class based components.

  System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
  Browsers:
    Chrome: 79.0.3945.130
    Safari: 13.0.5
  npmPackages:
    preact: ^10.2.1 => 10.2.1 
    preact-cli: 3.0.0-rc.4 => 3.0.0-rc.4 
    preact-render-to-string: ^5.1.3 => 5.1.3 
    preact-router: ^3.1.0 => 3.1.0

**Comment by psabharwal123** [comment]
@robertknight

**Comment by marvinhagemeister** [comment]
Are you sure about that? 

```jsx
class Foo {}
console.log(typeof Foo)
// Logs: "function"
```
So there is no difference in output when using the `typeof` keywords with classes or functions. We use this check quite a lot in core. If in your case `vnode.type` is really `undefined` then there must be something else going on.

**Comment by psabharwal123** [comment]
It seems to be related to using unistore context, I ll try to create a standalone case and close this for now.
