### ISSUE TITLE
No `LICENSE` file

### ISSUE THREAD

**Issue by wnayes** [preactjs/enzyme-adapter-preact-pure#93]
The `preact` project [has a LICENSE file](https://github.com/preactjs/preact/blob/master/LICENSE), but I don't see one here. I can see that the project.json suggests this is MIT licensed, but I don't know if that counts as "official" or not (Github does not indicate it as so). Could a LICENSE file be added?

**Comment by robertknight** [comment]
The license is indeed MIT, the [same as the main Preact project](https://github.com/preactjs/preact/blob/master/LICENSE). Would you mind submitting a PR to add the `LICENSE` file?
