### ISSUE TITLE
TypeError: your adapter does not support `wrappingComponent`. Try upgrading it!

### ISSUE THREAD

**Issue by gtsop** [preactjs/enzyme-adapter-preact-pure#99]
I am trying to use this in preact: https://github.com/styled-components/styled-components/issues/1319

But I get this error: 
```
TypeError: your adapter does not support `wrappingComponent`. Try upgrading it!
```

From what I managed to figure out, it means that this adapter should implement the `wrappingComponent` option but it doesn't as of now. Is that something that can be fixed?

**Comment by robertknight** [comment]
Support for `wrappingComponent` was added in https://github.com/preactjs/enzyme-adapter-preact-pure/pull/157, released in v3.4.0.
